name: icalendar_parser
description: Package to parse iCalendar (.ics) files written in pure Dart.
version: 0.4.1
homepage: https://github.com/TesteurManiak
repository: https://github.com/TesteurManiak/icalendar_parser

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.4
dependencies:
  meta: ^1.3.0
